name: delete workflow

on: [workflow_dispatch]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/${{ secrets.USERNAME }}
            unalias rm
            rm -rf CMSC389T-PersonalWebsite